# Project: calc_test
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = calculatorStack.o calculatorTree.o calculatorTest.o calculatorMain.o stackChar.o stackInt.o
LINKOBJ  = calculatorStack.o calculatorTree.o calculatorTest.o calculatorMain.o stackChar.o stackInt.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = calc_test.exe
CXXFLAGS = $(CXXINCS) -g3 -g
CFLAGS   = $(INCS) -g3 -g
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

calculatorStack.o: calculatorStack.c
	$(CC) -c calculatorStack.c -o calculatorStack.o $(CFLAGS)

calculatorTree.o: calculatorTree.c
	$(CC) -c calculatorTree.c -o calculatorTree.o $(CFLAGS)

calculatorTest.o: calculatorTest.c
	$(CC) -c calculatorTest.c -o calculatorTest.o $(CFLAGS)

calculatorMain.o: calculatorMain.c
	$(CC) -c calculatorMain.c -o calculatorMain.o $(CFLAGS)

stackChar.o: stackChar.c
	$(CC) -c stackChar.c -o stackChar.o $(CFLAGS)

stackInt.o: stackInt.c
	$(CC) -c stackInt.c -o stackInt.o $(CFLAGS)
